replicaCount: 1

image:
  repository: ghcr.io/c-neto/image-renamer-admission-plugin
  tag: main
  pullPolicy: Always

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lRRWUwMG1RVm5kM1UzQ1A1L0VKc0ppVEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTFNRE14TmpFME1EZ3hNVm9YRFRJMU1EWXhOREUwTURneE1Wb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSytVYkYwcUU4cWV3d3liTldDc3A0Rkc5bjVmbjB0NjNSVlJZd0p2Cm1nbGIxZ0RMUDJzTkptWkVRVXRQZGdCaE40aTkramdYczVaTDNFaDBYZ200N1FRV2JlVDBzVFFDdVA5ZlBLeTcKalBsR3kxYndxZHBFL3E5TUQrbjcxcm5RZWQzVVVISlBxMXFuRkFPSXRjUUxsN2JvK1NzSlBTM2p4OFFaaTRFMApqdTN4c1BYS2k1WHBPVDIyOGxsWkx2UUhYd1NwK0Iwbml0WHNxY05MWVVpOHc4SzdWVzRFRWZpSit2RWRqWS9ECkNGS3Bta1NyTy9xWFExTkptVHB2czhYNWx2ZnVvbzVqamVaeTlLK1dSbHJ6ZTlqUTV3eS94Zk1lUGtMamVoUTIKWm9sZndlTUowTDBqUjg2aXdkY2w5T25KWFp3M1lZYnNhM1hIMHh0cTF0SmJGbXNDQXdFQUFhTi9NSDB3SFFZRApWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd1RnWURWUjBSCkFRSC9CRVF3UW9JWWNtVnNaV0Z6WlMxdVlXMWxMbVJsWm1GMWJIUXVjM1pqZ2laeVpXeGxZWE5sTFc1aGJXVXUKWkdWbVlYVnNkQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBV0llWApsdGMzYVg5d3ViZWJBZ2xQZnpEUHNNeEowQ1pmYWdvT3FmR0cvb1NTMGplZFBSQTV6Uy93UWNScFR3RjJUQmZwCmdRWGdkQlZtMmo2MXRSRU15Vk52Mk54emovL1pmcVpadEJzM1RmU3lJbFZLL2IrUFN0RWllV2tKYVZMRGVyaHcKQlpzejdIK1BIK052MjV5VTg4VEJGZzloL25Rc3d4Sk0zRE9GY1hLUVF3OUNYZ2toNm1QeFUxR3J5OWFuclplRwpFV1RFM2M5dDQwbmhVS1BoN2xOMnNmWlZFY2V0YjB0Y1Z4RDliT01WaGZmK29JbDVHSGZ5QmpIRnY4WVRJYXgyClgzS1JBN2dkbWVwRU9YcE45blRoTDdkUWpvRVBuRXRJK0tsREg1T0tPckVIQlYwd0w5cEdYOVlCOExJMHRGdGIKSGtrbi81OW1DTDI3NWNldk5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=