replicaCount: 1

image:
  repository: ghcr.io/c-neto/image-renamer-admission-plugin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

caBundle: ""
