---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.example.com
  resources:
  - podwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.example.com
  resources:
  - podwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - core.example.com
  resources:
  - podwatchers/status
  verbs:
  - get
  - patch
  - update
