apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-renamer-admission-plugin.fullname" . }}
  labels:
    {{- include "image-renamer-admission-plugin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-renamer-admission-plugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "image-renamer-admission-plugin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tls-certs
              mountPath: /tls
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: image-renamer-admission-plugin-tls
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
