apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-renamer-admission-plugin.fullname" . }}
  labels:
    {{- include "image-renamer-admission-plugin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
    - port: 443
      targetPort: 8443
  selector:
    {{- include "image-renamer-admission-plugin.selectorLabels" . | nindent 4 }}
