apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: image-renamer-admission-plugin-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-renamer-admission-plugin-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "image-renamer-admission-plugin.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "image-renamer-admission-plugin.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  secretName: image-renamer-admission-plugin-tls
  commonName: {{ include "image-renamer-admission-plugin.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: image-renamer-admission-plugin-selfsigned-issuer
    kind: ClusterIssuer
  isCA: true
  usages:
    - server auth
    - client auth
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mutant-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: root-secret
