apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-renamer-admission-plugin-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "image-renamer-admission-plugin.fullname" . }}.{{ .Release.Namespace }}.svc
  secretName: image-renamer-admission-plugin-tls
  issuerRef:
    name: image-renamer-admission-plugin-selfsigned-issuer
    kind: Issuer
