apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "image-renamer-admission-plugin.fullname" . }}
webhooks:
  - name: image-renamer-admission-plugin.k8s.io
    clientConfig:
      service:
        name: {{ include "image-renamer-admission-plugin.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
      caBundle: {{ .Values.caBundle }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    sideEffects: None
