name: Build and Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: helm package deploy/helm/image-renamer-admission-controller

      - name: Publish Helm chart
        run: |
          helm push image-renamer-admission-controller-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
